### ISSUE TITLE
Reuse ${DLC} in Task?

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#224]
Hi,

Is there a way to reuse the ${DLC} environment variable that gets set through the abl.configuration.runtimes in settings.json?
To run an OpenEdge application from VSCode you need to create a Task.
That task specifies the path to prowin.exe in the "command" element.
Ideally I would like to specify "${DLC}/bin/prowin.exe" so the Tasks.json file can be checked in and distributed to the other developers.
I have a workaround: create DLC128/DLC122/DLC117 OS or user environment variables and use these in the command of the task. This works but is yet another step that everyone should apply in setting up an environment with VSCode...

**Comment by gquerret** [comment]
I'll check if VS Code allows such injection of variables.

**Comment by cverbiest** [comment]
Not really DLC, but this may help.

You can use config variables in tasks

```
{

    "version": "2.0.0",
    "tasks": [
        {
            "label": "Test with config variable",
            "type": "shell",
            "command": "OE is ${config:abl.configuration.defaultRuntime}"
        }
    ]
}
```

**Comment by gquerret** [comment]
Thanks for tip @cverbiest, it looks like it will be possible to inject the DLC variable returned by the extension.

**Comment by cverbiest** [comment]
${env:DLC} should work, if DLC is set in the OS

**Comment by gquerret** [comment]
Fixed, will be available in next pre-release. Note that tasks have to use `"type": "shell"` and not `"type": "process"`, otherwise the command result is expanded as a relative path (VS Code issue [https://github.com/microsoft/vscode/issues/160891](https://github.com/microsoft/vscode/issues/160891) ).

Example:

```
    {
      "label": "Debugger01",
      "type": "shell",
      "command": "${command:abl.getDlcDirectory}\\bin\\prowin.exe",
      "args": [
        "-db", "db/sp2k", "-ld", "sports", "-RO",
        "-ininame", "conf/gui.ini",
        "-p", "debugger01.p",
        "-nosplash",
        "-debugReady", "3099",
        "-zdlc", "${command:abl.getDlcDirectory}"
      ],
    }
```

**Comment by lievendf** [comment]
@gquerret , I've now had it on 2 occasions that the new ${command:abl.getDlcDirectory} command returns blank causing a task to fail.
This does not always happen though...
I have 2 tasks in my tasks.json, both using the command in the same way, and for one it returns the correct value (visible in terminal) while in the other it returns empty string (also visible in terminal).
Any idea what could be causing this?

**Comment by gquerret** [comment]
A fix is already available, the new version will be released this morning.

Pre-releases are sometimes broken ;-)

**Comment by lievendf** [comment]
@gquerret , I have 1.13.5 (pre-release) but still have the command return blank:

tasks.json:
```
{
    "label": "Run As Test",
    "type": "shell",
    "command": "${command:abl.getDlcDirectory}/bin/prowin.exe",
```

Console output:
```
Executing task in folder <workspace_folder>: /bin/prowin.exe -basekey ini -ininame ... <redacted>

'/bin/prowin.exe' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by lievendf** [comment]
> Your task is defined in the workspace, not in a project ?

No, sorry, I adjusted the Console output to read "project_folder" instead of "workspace_folder".
The tasks.json file is in my projects .vscode folder.
